<div class="footertop">
	<div class="quicklink">
		<div class="quicklinkbox">
			<div class="quicklinkboxtitle">配送范围</div>
			<ul>
				<li>
				<a href="#" target="_blank">上海</a>
				&nbsp;|&nbsp;
				<a href="#">北京</a>
				&nbsp;|&nbsp;
				<a href="#">其他地区</a>
				</li>
				<li>
				<a href="#" target="_blank">配送费收取标准</a>
				</li>
			</ul>
		</div>
		<div class="quicklinkbox">
			<div class="quicklinkboxtitle">服务说明</div>
			<ul>
				<li>
				<a href="#" target="_blank">付款方式</a>
				</li>
				<li>
				<a href="#" target="_blank">服务协议</a>
				</li>
			</ul>
		</div>
		<div class="quicklinkbox">
			<div class="quicklinkboxtitle">我的订单</div>
			<ul>
				<li>
				<a href="#" target="_blank">查询订单</a>
				</li>
				<li>
				<a href="#" target="_blank">如何下订单</a>
				</li>
			</ul>
		</div>
		<div class="quicklinkbox">
			<div class="quicklinkboxtitle">售后服务</div>
			<ul>
				<li>
				<a target="_blank" href="#">退换货原则</a>
				</li>
				<li>
				<a target="_blank" href="#">延保服务</a>
				</li>
			</ul>
		</div>
		<div class="quicklinkbox">
			<div class="quicklinkboxtitle">需要帮助</div>
			<ul>
				<li>
				<a target="_blank" href="#">忘记密码</a>
				</li>
				<li>
				<a target="_blank" href="#">常见问题</a>
				</li>
				<li>
				<a target="_blank" href="#">联系客服</a>
				</li>
				<li>
				<a target="_blank" href="#">抵用券使用说明</a>
				</li>
			</ul>
		</div>
		<div class="quicklinkbox">
			<div class="quicklinkboxtitle">商家入驻</div>
			<ul>
				<li>
				<a target="_blank" href="#">立即入驻</a>
				</li>
				<li>
				<a target="_blank" href="#">入驻热点问题</a>
				</li>
			</ul>
		</div>
	</div>
</div>