<div class="header_wrap">
	<div id="index_header">
		<ul class="topnav"> 
			<li>欢迎来到买多多</li>
		</ul>
		<div class="clear"></div>
		<div class="dcenter">
			<a class="fl" href="">
			<img src="/images/logo.png" alt="moretobuy" />
			</a>
			<div id="global_menu" class="dnav fr">
				<span class="select"><a href="">首页</a></span>
				<span class=""><a href="">水果图片</a></span>
				<span class=""><a href="">水果介绍</a></span>
			</div>
		</div>
		<div class="bottom">
			<div id="allCategoryHeader" class="category fl color_white_none">
				<h2><a href="#">所有商品分类</a></h2>
			</div>
			<div id="ap_category" class="ap_category">
				<img class="cateicon" src="http://image.yihaodianimg.com/statics/global/images/navicon.gif">
				<ul id="menuList">
					<li class="ap_listeg border_ap_listeg pointer">
						<span class="ap_listegfont">
							<a title="食品、饮料、酒水" style="color:#333333;" href="#">食品、饮料、酒水</a>
						</span>
					</li>
					<li class="ap_listeg border_ap_listeg pointer">
						<span class="ap_listegfont">
							<a title="美容化妆、个人护理" style="color:#333333;" href="#">美容化妆、个人护理</a>
						</span>
					</li>
					<li class="ap_listeg border_ap_listeg pointer">
						<span class="ap_listegfont">
							<a title="母婴食品、母婴用品" style="color:#333333;" href="#">母婴食品、母婴用品</a>
						</span>
					</li>
					<li class="ap_listeg border_ap_listeg pointer">
						<span class="ap_listegfont">
							<a title="厨房用品、清洁用品" style="color:#333333;" href="#">厨房用品、清洁用品</a>
						</span>
					</li>
					<li class="ap_listeg border_ap_listeg pointer">
						<span class="ap_listegfont">
							<a title="手机通讯、数码电器" style="color:#333333;" href="#">手机通讯、数码电器</a>
						</span>
					</li>
					<li class="ap_listeg border_ap_listeg pointer">
						<span class="ap_listegfont">
							<a title="大家电、生活电器" style="color:#333333;" href="#">大家电、生活电器</a>
						</span>
					</li>
					<li class="ap_listeg border_ap_listeg pointer">
						<span class="ap_listegfont">
							<a title="电脑,软件,办公用品" style="color:#333333;" href="#">电脑,软件,办公用品</a>
						</span>
					</li>
					<li class="ap_listeg border_ap_listeg pointer">
						<span class="ap_listegfont">
							<a title="家居汽饰、箱包运动" style="color:#333333;" href="#">家居汽饰、箱包运动</a>
						</span>
					</li>
					<li class="ap_listeg border_ap_listeg pointer">
						<span class="ap_listegfont">
							<a title="玩具、图书音像" style="color:#333333;" href="#">玩具、图书音像</a>
						</span>
					</li>
					<li class="ap_listeg border_ap_listeg pointer">
						<span class="ap_listegfont">
							<a title="服装鞋包" style="color:#333333;" href="#">服装鞋包</a>
						</span>
					</li>
					<li class="ap_listeg border_ap_listeg pointer">
						<span class="ap_listegfont">
							<a title="营养保健、健康器械" style="color:#333333;" href="#">营养保健、健康器械</a>
						</span>
					</li>
					<li class="ap_listeg border_ap_listeg pointer">
						<span class="ap_listegfont">
							<a title="机票、充值、健康" style="color:#333333;" href="#">机票、充值、健康</a>
						</span>
					</li>
				</ul>
			</div>
			<div class="searchbox fl">
				<div class="inputbox fl f14">
					<div class="input_search">
						<input id="keyword" type="text" autocomplete="off" maxlength="100" value="" name="keyword" style="color: rgb(153, 153, 153);" />
					</div>
				</div>
				<div class="search fl">
					<img src="http://image.yihaodianimg.com/statics/global/images/index/btn_search.jpg" />
				</div>
			</div>
			<div id="hotKeywordsShow" class="keyword fl">
			</div>
			<div id="scrollCart" class="shopcartbox fl">
			</div>
		</div>
	</div>
</div>