<div class="banner pt10 mb10">
	<a title="" target="_blank" href="#">
		<img style="width:765px;height:60px;" src="http://d1.yihaodianimg.com/t4/2011/11/28/3639216.jpg">
	</a>
</div>
<div class="center">
	<div class="left fl">
		<div id="flash_div_id" class="flash">
			<div id="first_banner_slider" class="flashpic" style="overflow:hidden;position:relative;">
				<div class="panel-container" style="height: 1750px; margin-top: 0px;">
					<div class="panel" style="display: block; float: left; width: 550px;">
						<a target="_blank" href="#">
						<img width="550" heigth="175" src="http://d1.yihaodianimg.com/t4/2011/11/25/3623804.jpg">
						</a>
					</div>
				</div>
			</div>
		</div>
		<div class="lowarea mt10">
			<div id="second_banner_slider" class="fl lowareabox" style="overflow:hidden;position:relative;">
				<div class="panel-container" style="width: 960px;">
					<div class="panel" style="width: 480px; height: 140px; display: block; float: left;">
						<img width="550" heigth="175" src="http://d2.yihaodianimg.com/t4/2011/12/02/3722312.jpg">
					</div>
				</div>
			</div>
		</div>
	</div>
</div>